### ISSUE TITLE
How can I create a .xpi file of this addon to install it in Firefox?

### ISSUE THREAD

**Issue by YousufSSyed** [0ui/gif-scrubber#9]

**Comment by notetiene** [comment]
Please inlude at least a short description when making issues.

From what I remember, this extension could work on Firefox, but we would need to check that the manifest.json is compatible with Firefox.

**Comment by notetiene** [comment]
@YousufSSyed I just made a fork to add support for Firefox. See https://github.com/notetiene/gif-scrubber.  I might make an XPI when I get time (or upload it to AMO).

**Comment by YousufSSyed** [comment]
Could you also add instructions user to compile an .xpi themselves?

**Comment by notetiene** [comment]
From what I remember, you won't be able to install .xpi themselves unless it's signed.

See : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

**Comment by YousufSSyed** [comment]
I meant sideloading the .xpi, installing it from a local file rather than from the Mozilla Addon store. Its not that I wouldn't want to, its that I'd want the option to do it myself if the addon stops being maintained for some reason.

**Comment by notetiene** [comment]
It's no longer possible to sideload extensions without signing them in default Firefox edition.  Due to past abuses, it was decided that extensions would need to be signed in order to be sideloaded.

See [1] for instructions.

There's still this workaround for other editions to bypass signing it [2].  I wouldn't recommend using this method.

[1] https://extensionworkshop.com/documentation/publish/distribute-sideloading/
[2] https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/

**Comment by notetiene** [comment]
@YousufSSyed The extension would be ready to submit to AMO, but unless I make an explicit fork, I would have to ask explicit permission to change the extension name so that it would appear as a fork.

@0ui Would you be okay if I submit the extension to AMO?  The Mozilla extension review process can sometimes be long.

**Comment by 0ui** [comment]
I never made a Firefox extension in the past because the API was so different, but now, years later, it seems that Firefox largely supports the same API. I just tried loading in Firefox and to my delight it works very well. I'll make some small changes and attempt to submit to AMO.

@notetiene If you'd still rather go your own route, you're correct I'd ask that you choose another name/logo/identity to submit with. But hopefully my submission will be easy enough for everyone to use.

**Comment by notetiene** [comment]
@0ui Seriously, I see no reason to make a fork now!

**Comment by 0ui** [comment]
Awaiting approval now. It will appear here when approved https://addons.mozilla.org/en-US/firefox/addon/gif-scrubber3/

I guess someone already used the slug `gif-scrubber` lol

**Comment by YousufSSyed** [comment]
And its' been approved!

**Comment by 0ui** [comment]
I'll consider this closed and address the other issues separately
